### ISSUE TITLE
Error: ‘string’ in namespace ‘std’ does not name a type

### ISSUE THREAD

**Issue by AJRdev** [eteran/edisassm#2]
Hi,
After a fresh clone of your repo and following your instructions, I got this error message while using your Makefile : 

`In file included from edisassm/Instruction.cpp:19:0:
edisassm/include/edisassm/Instruction.h:1359:7: error: ‘string’ in namespace ‘std’ does not name a type
  std::string mnemonic() const                      { return opcode_->mnemonic; }
CMakeFiles/edisassm.dir/build.make:62: recipe for target 'CMakeFiles/edisassm.dir/Instruction.cpp.o' failed
make[2]: *** [CMakeFiles/edisassm.dir/Instruction.cpp.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/edisassm.dir/all' failed
make[1]: *** [CMakeFiles/edisassm.dir/all] Error 2
Makefile:94: recipe for target 'all' failed
make: *** [all] Error 2
`

I just fixed it by adding a `#include <string>` in the **Instruction.h** file but I imagine you have a global header for these kind of includes ?

Regards, 
Andre.

**Comment by eteran** [comment]
Hi,

Your fix is a appropriate and I've applied it to my repo. So thank you 👍 

That being said, to be honest, edisassm is a bit of a deprecated project. It is no longer the disassembler for my edb project, which has switched to capstone. While I would have l loved for edisassm to "take off" in the open source world, capstone seems to be the disassembler of course.

I do think that edisassm is a quality disassembler, but just as heads up, I don't expect to be working on it for the forseable future, which includes future expansions to the x86 architecture.
